import { pgType, TypefusionDbScript } from "../../src/index.js";

const allPgTypes = {
  text: pgType.text().notNull(),
  integer: pgType.integer().notNull(),
  boolean: pgType.boolean().notNull(),
  date: pgType.date().notNull(),
  dateTime: pgType.dateTime().notNull(),
  bigint: pgType.bigint().notNull(),
  smallint: pgType.smallint().notNull(),
  real: pgType.real().notNull(),
  doublePrecision: pgType.doublePrecision().notNull(),
  smallserial: pgType.smallserial().notNull(),
  serial: pgType.serial().notNull(),
  bigserial: pgType.bigserial().notNull(),
  numeric: pgType.numeric().notNull(),
  decimal: pgType.decimal().notNull(),
  money: pgType.money().notNull(),
  char: pgType.char(10).notNull(),
  varchar: pgType.varchar(50).notNull(),
  time: pgType.time().notNull(),
  interval: pgType.interval().notNull(),
  point: pgType.point().notNull(),
  line: pgType.line().notNull(),
  lseg: pgType.lseg().notNull(),
  box: pgType.box().notNull(),
  polygon: pgType.polygon().notNull(),
  circle: pgType.circle().notNull(),
  inet: pgType.inet().notNull(),
  cidr: pgType.cidr().notNull(),
  macaddr: pgType.macaddr().notNull(),
  tsvector: pgType.tsvector().notNull(),
  tsquery: pgType.tsquery().notNull(),
  uuid: pgType.uuid().notNull(),
  json: pgType.json().notNull(),
  jsonb: pgType.jsonb().notNull(),
  xml: pgType.xml().notNull(),
  bytea: pgType.bytea().notNull(),
};

export default {
  name: "typefusion_all_pg_types",
  schema: allPgTypes,
  resultDatabase: "postgresql",
  run: async () => {
    console.log("TYPEFUSION ALL PG TYPES IS RUN");
    return {
      data: [
        {
          text: "Sample text",
          integer: 42,
          boolean: true,
          date: new Date("2023-05-17"),
          dateTime: new Date("2023-05-17T12:34:56"),
          bigint: BigInt("9007199254740991"),
          smallint: 32767,
          real: 3.14,
          doublePrecision: 3.141592653589793,
          smallserial: 12345,
          serial: 123456,
          bigserial: BigInt("9223372036854775807"),
          numeric: 123.45,
          decimal: 678.9,
          money: 1234.56,
          char: "Fixed     ",
          varchar: "Variable length text",
          time: "12:34:56",
          interval: "1 year 2 months 3 days 4 hours 5 minutes 6 seconds",
          point: "(1,2)",
          line: "{1,-1,0}",
          lseg: "((1,1),(2,2))",
          box: "((1,1),(2,2))",
          polygon: "((0,0),(1,1),(2,0))",
          circle: "<(0,0),1>",
          inet: "192.168.0.1",
          cidr: "192.168.0.0/24",
          macaddr: "08:00:2b:01:02:03",
          tsvector: "'a':1 'sample':2 'text':3",
          tsquery: "'sample' & 'query'",
          uuid: "123e4567-e89b-12d3-a456-426614174000",
          json: { key: "value" },
          jsonb: { anotherKey: "anotherValue" },
          xml: "<root><element>content</element></root>",
          bytea: new Uint8Array([0x12, 0x34, 0x56, 0x78]),
        },
      ],
    };
  },
} satisfies TypefusionDbScript<typeof allPgTypes>;
